// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Subsystems/DriveTrain.h"
#include "Commands/Drive.h"

Drive::Drive(std::shared_ptr<DriveTrain> drive_train, 
             std::function<double()> left_speed_func, 
             std::function<double()> right_speed_func) : frc::Command() 
{
    std::cout << "Drive constructer" << std::endl;
    drive_train_ = drive_train;
    left_speed_func_ = left_speed_func;
    right_speed_func_ = right_speed_func;

    Requires(drive_train_.get());

    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());

}

// Called just before this Command runs the first time
void Drive::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Drive::Execute() {
   // std::cout << "Drive::Execute" << std::endl; 
    drive_train_->Drive(left_speed_func_(), right_speed_func_());
}

// Make this return true when this Command no longer needs to run execute()
bool Drive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Drive::End() {
    drive_train_->Drive(0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Drive::Interrupted() {

}
