// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include <frc/util/color.h>
#include "frc/DigitalInput.h"
#include "rev/ColorSensorV3.h"
#include "rev/ColorMatch.h"

#include "frc/commands/Subsystem.h"

class ControlPanel: public frc::Subsystem {
private:
  std::unique_ptr<rev::ColorSensorV3> color_sensor_;
public:

	ControlPanel();
	void InitDefaultCommand() override;
	void Periodic() override;
	frc::Color ReadColor();
};

