// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Constants.h"
#include <frc/TimedRobot.h>
#include <frc/smartdashboard/smartdashboard.h>
#include <frc/util/color.h>
#include "Subsystems/ControlPanel.h"
#include "rev/ColorSensorV3.h"
#include "rev/ColorMatch.h"

ControlPanel::ControlPanel() : frc::Subsystem("controlPanel") 
{
    std::cout << "ControlPanel constructer" << std::endl;
    static constexpr auto i2cPort = frc::I2C::Port::kOnboard;
	color_sensor_.reset(new rev::ColorSensorV3(i2cPort));
}

void ControlPanel::InitDefaultCommand() 
{

}

void ControlPanel::Periodic() 
{

}

frc::Color ControlPanel::ReadColor()
{
    frc::Color detected_color = color_sensor_->GetColor();
    std::cout << "color sensor [R:" << detected_color.red 
                            << "G:"<< detected_color.green 
                            << "B:" << detected_color.blue << "]" << std::endl;
    return detected_color;
}
